pygments: true
permalink: /otter-pop/:year/:month/:day/:title
markdown: rdiscount
exclude: ['.git']
name: "Otter Popper"
description: "The world's greated jekyll theme Boi"
url: http://roachhd.github.io/otter-pop/
